version: "3"
services:
  Website:
    build: ./react-app
    image: website
    ports:
      - "801:3000"
    restart: unless-stopped
    networks:
      portfolio_website:
        ipv4_address: "192.168.1.3"
  WebsiteAPI:
    build: ./express-app
    image: website_api
    ports:
      - "901:5000"
    restart: unless-stopped
    networks:
      portfolio_website:
        ipv4_address: "192.168.1.4"

networks:
  portfolio_website:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
